plugin.class=com.ghostchu.biglyplug.torrentsizelimiter.Plugin
plugin.name=BiglyBT-TorrentSizeLimiter
plugin.langfile=com.ghostchu.biglyplug.torrentsizelimiter.Messages
plugin.id=ghostchutorrentsizelimiter
plugin.version=${project.version}